### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by jpashayev** [sergiandreplace/planets-flutter#5]
I recently downloaded all the files. First page appears just fine, but whenever I try to click or scroll an exception is caught. I've tried a few things but haven't been able to understand why.

![pic1](https://user-images.githubusercontent.com/40347155/41515835-1d105376-7266-11e8-83a1-c519de7e4f8b.PNG)
![pic2](https://user-images.githubusercontent.com/40347155/41515850-335f01d6-7266-11e8-88c3-e84b8623eb11.PNG)

**Comment by martinory** [comment]
Hello,
Try change this line in Routes.dart:
`return new PlanetDetailPage(params["id"]);`
To:
`return new PlanetDetailPage(params["id"][0]);`
Hope it works!
